trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  # This must match the 'Service connection name' you typed in the popup
  azureServiceConnection: 'AzureWebAppConnection' 
  # This must match the name of the App Service in your portal
  webAppName: 'enthashoppingundo'

steps:
# --- BUILD STAGE ---
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

- task: NuGetCommand@2
  displayName: 'Restore NuGet Packages'
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: 'Build Solution & Create Zip'
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# --- TEST STAGE ---
- task: VSTest@2
  displayName: 'Run Unit Tests'
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# --- DEPLOY STAGE ---
- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy to Azure Web App'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: '$(azureServiceConnection)'
    appType: 'webApp'
    WebAppName: '$(webAppName)'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'