name: Build and deploy ASP.NET MVC to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore DevikaBookingManagement.sln

      - name: Build Solution
        run: msbuild DevikaBookingManagement.sln /p:Configuration=Release

      - name: Publish Web Project
        run: |
          msbuild DevikaBookingManagement/DevikaBookingManagement.csproj ^
          /p:DeployOnBuild=true ^
          /p:WebPublishMethod=FileSystem ^
          /p:PublishUrl=${{ github.workspace }}\publish ^
          /p:Configuration=Release

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_XXXXX }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_XXXXX }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_XXXXX }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: enthashoppingundo
          package: publish
