name: Build and Deploy ASP.NET MVC to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    permissions:
      id-token: write
      contents: read

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup build tools
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      # Restore solution
      - name: Restore NuGet packages
        run: nuget restore DevikaBookingManagement.sln

      # Build solution
      - name: Build Solution
        run: msbuild DevikaBookingManagement.sln /p:Configuration=Release

      # Publish Web Project to folder
      - name: Publish Web Project
        run: |
          msbuild DevikaBookingManagement/DevikaBookingManagement.csproj `
              /p:DeployOnBuild=true `
              /p:WebPublishMethod=FileSystem`
              /p:Configuration=Release `
              /p:WebPublishMethod=FileSystem `
              /p:PublishUrl="${{ github.workspace }}\publish"

      # Verify publish folder
      - name: Verify Publish Folder
        run: dir "${{ github.workspace }}\publish"

      # Create ZIP for Azure deployment
      - name: Create ZIP package
        run: powershell Compress-Archive -Path "${{ github.workspace }}\publish\*" -DestinationPath "${{ github.workspace }}\site.zip"

      - name: Verify ZIP
        run: dir "${{ github.workspace }}\site.zip"

      # Azure Login
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_665AAC9768764F6AA8CE3E2842F43BEB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B1031CB56AFC4975873A8B3CE92DC7AC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3326E556FC4A4EFABA5C07FCE65E7B42 }}

      # Deploy
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: enthashoppingundo
          package: "${{ github.workspace }}\\site.zip"

